version: '3'

services:
  db:
    build: ./pg
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    networks:
      - test_network
  python:
    build: ./python
    networks:
      - test_network
  web:
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - db
      - python
    networks:
      - test_network

networks:
  test_network:

